#cloud-config
users:
  - default
  - name: operador
    password: $6$hRJb7e8G4BWzN0dM$k2/T/qPgYU/Ae1KD3sZO.cLQyu9Xb.p5Cw17JfAHq6gB0F7bvhTvgFx5BHVaGV7/WrT38fM6d4WzR/
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: [wheel, audio, video]
    lock_passwd: false
  - name: ubuntu
    password: $6$hRJb7e8G4BWzN0dM$k2/T/qPgYU/Ae1KD3sZO.cLQyu9Xb.p5Cw17JfAHq6gB0F7bvhTvgFx5BHVaGV7/WrT38fM6d4WzR/
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: [wheel, audio, video]
    lock_passwd: false
  - name: ubuntu-cloudguest
    password: $6$hRJb7e8G4BWzN0dM$k2/T/qPgYU/Ae1KD3sZO.cLQyu9Xb.p5Cw17JfAHq6gB0F7bvhTvgFx5BHVaGV7/WrT38fM6d4WzR/
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: [wheel, audio, video]
    lock_passwd: false

package_update: true
package_upgrade: true
packages:
  - flatpak
  - discord
  - anydesk
  - google-chrome-stable
  - spotify
  - network-manager-openvpn-gnome
  - openvpn
  - network-manager-openconnect-gnome
  - openconnect
  - openresolv-conf
  - xorg

# Instalar Flatpak e adicionar o repositório Flathub
write_files:
  - path: /etc/apt/sources.list.d/flatpak.list
    owner: root:root
    content: |
      deb https://flathub.org/repo/flathub.flatpakrepo stable main
  - path: /etc/systemd/system/graphical.target.wants/display-manager.service
    owner: root:root
    content: |
      [Unit]
      Description=Display Manager
      After=network.target
      [Service]
      ExecStart=/usr/bin/xdg-su -l -c '/etc/X11/Xsession /etc/X11/xinit/xinitrc'
      [Install]
      WantedBy=graphical.target
# Configurar o adaptador de rede sem fio
network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
  wifis:
    wlo1:
      optional: true
      access-points:
        SmartBR_Wifi:
          password: "p1nc3l@sm4rtbr2021"
      dhcp4: true
