#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'operador'
        hostname: ubuntu-desktop
        username: operador
        password: '$6$rounds=4096$Ib8YPS3Q1KSXgePG$gZmGTgTFih7G.9MHHPx7/yVFdI.t34hlMvOpysHlHc2XNdLean.X0qZEIqANY.KpF0en27mcW/LsMam39QhhW1'  # Senha criptografada
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    packages:
        - libreoffice
        - gimp
        - git
        - wget
        - anydesk
        - ocsinventory-agent
        - binutils
        - openjdk-11-jdk
        - openjdk-8-jdk
        - unzip
        - ttf-mscorefonts-installer
        - curl
        - python3-pycurl
        - docker.io
        - freeipa-client
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    late-commands:
        - |
          cat > /target/root/install-extra.sh << 'EOF'
          #!/bin/bash

          # Atualizar a lista de pacotes
          apt-get update

          # Instalar o Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -i google-chrome-stable_current_amd64.deb
          apt-get install -f -y

          # Instalar o DBeaver
          wget https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
          dpkg -i dbeaver-ce_latest_amd64.deb
          apt-get install -f -y

          # Instalar o Discord
          wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb"
          dpkg -i discord.deb
          apt-get install -f -y

          # Instalar o Master PDF Editor
          wget -c https://code-industry.net/public/master-pdf-editor-5.8.70-qt5.x86_64.deb
          dpkg -i master-pdf-editor-5.8.70-qt5.x86_64.deb
          apt-get install -f -y

          # Instalar o AnyDesk
          wget -c https://download.anydesk.com/linux/anydesk_6.1.1-1_amd64.deb -O AnyDesk.deb
          dpkg -i AnyDesk.deb
          apt-get install -f -y

          # Instalar o Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          groupadd docker
          usermod -aG docker $USER

          # Instalar o NetBeans 12
          mkdir -p /home/$USER/Netbeans_Instalador
          cd /home/$USER/Netbeans_Instalador
          wget https://archive.apache.org/dist/netbeans/netbeans/12.5/Apache-NetBeans-12.5-bin-linux-x64.sh
          chmod +x Apache-NetBeans-12.5-bin-linux-x64.sh
          ./Apache-NetBeans-12.5-bin-linux-x64.sh --silent

          # Configurar o FreeIPA Client
          ipa-client-install --mkhomedir

          # Mudar a senha do root
          echo "root:1nfr4@2023" | chpasswd

          # Finalizar
          echo "Instalação concluída!"
          EOF
        - chmod +x /target/root/install-extra.sh
        - chroot /target /root/install-extra.sh
